"""eSewa XLS statement parser.

Parses the legacy XLS (BIFF) format exported from eSewa.
Sheet: 'eSewa Report'
Columns: Reference Code, Date Time, Description, Dr., Cr., Status, Balance (NPR), Channel
Order: newest-first

Reference Code is NOT unique per financial row — deduplication uses full fingerprint.
"""

import logging
from datetime import datetime, date, timezone
from decimal import Decimal, InvalidOperation
from typing import Optional

import xlrd

from app.parsers.base import ParsedStatement, ParsedTransaction, StatementParser

logger = logging.getLogger(__name__)

# Expected column headers (case-insensitive matching)
EXPECTED_HEADERS = [
    "reference code",
    "date time",
    "description",
    "dr.",
    "cr.",
    "status",
    "balance (npr)",
    "channel",
]

# Column indices after header detection
COL_REFERENCE = 0
COL_DATETIME = 1
COL_DESCRIPTION = 2
COL_DEBIT = 3
COL_CREDIT = 4
COL_STATUS = 5
COL_BALANCE = 6
COL_CHANNEL = 7


class EsewaStatementParser(StatementParser):
    """Parser for eSewa legacy XLS statement exports."""

    def parse(self, file_bytes: bytes, filename: str) -> ParsedStatement:
        workbook = xlrd.open_workbook(file_contents=file_bytes)

        # Find the 'eSewa Report' sheet
        sheet = None
        for name in workbook.sheet_names():
            if name.strip().lower() == "esewa report":
                sheet = workbook.sheet_by_name(name)
                break

        if sheet is None:
            return ParsedStatement(
                source="ESEWA",
                errors=["Sheet 'eSewa Report' not found in workbook"],
            )

        result = ParsedStatement(source="ESEWA", currency="NPR")

        # Find header row
        header_row_idx = self._find_header_row(sheet)
        if header_row_idx is None:
            result.errors.append("Could not locate transaction header row")
            return result

        # Extract metadata from rows above header
        self._extract_metadata(sheet, header_row_idx, result)

        # Parse transactions starting after header
        transactions = []
        row_errors = []

        for row_idx in range(header_row_idx + 1, sheet.nrows):
            row_values = [sheet.cell_value(row_idx, col) for col in range(sheet.ncols)]

            # Skip empty rows
            if all(v == "" or v is None for v in row_values):
                continue

            # Detect Total row or summary rows
            first_cell = str(row_values[0]).strip().lower() if row_values[0] else ""
            if first_cell in ("total", "pending", "complete", "canceled", "time out"):
                # Extract totals from the Total row
                if first_cell == "total" and not isinstance(row_values[0], float):
                    self._extract_totals(row_values, result)
                continue

            # Check if this looks like a summary count row (e.g., "Total    41")
            # These rows have a label in col 0 and a count — not transaction data
            if self._is_summary_row(row_values):
                continue

            # Try to parse as a transaction
            txn = self._parse_transaction_row(
                row_values, row_idx, sheet, row_errors
            )
            if txn is not None:
                transactions.append(txn)

        result.transactions = transactions
        if row_errors:
            result.errors.extend(row_errors)

        return result

    def _find_header_row(self, sheet) -> Optional[int]:
        """Locate the transaction header row by matching expected column names."""
        for row_idx in range(min(20, sheet.nrows)):
            row_values = [
                str(sheet.cell_value(row_idx, col)).strip().lower()
                for col in range(min(sheet.ncols, 8))
            ]
            # Check if this row contains the expected headers
            if len(row_values) >= 8 and row_values[0] == "reference code":
                return row_idx
        return None

    def _extract_metadata(
        self, sheet, header_row_idx: int, result: ParsedStatement
    ) -> None:
        """Extract statement metadata from rows above the header."""
        for row_idx in range(header_row_idx):
            if sheet.ncols < 2:
                continue
            label = str(sheet.cell_value(row_idx, 0)).strip().lower()
            value = sheet.cell_value(row_idx, 1)

            if label == "from date" and value:
                result.period_from = self._parse_date_value(value, sheet, row_idx, 1)
            elif label == "to date" and value:
                result.period_to = self._parse_date_value(value, sheet, row_idx, 1)
            elif label == "generated by" and value:
                # The value could be float in Excel if it's a number, so convert to string cleanly
                if isinstance(value, float):
                    result.account_number = str(int(value)).strip()
                else:
                    result.account_number = str(value).strip()

    def _parse_date_value(self, value, sheet, row_idx: int, col_idx: int) -> Optional[date]:
        """Parse a date value from an XLS cell."""
        if isinstance(value, float):
            try:
                dt_tuple = xlrd.xldate_as_tuple(value, sheet.book.datemode)
                return date(dt_tuple[0], dt_tuple[1], dt_tuple[2])
            except Exception:
                pass
        # Try string parsing
        try:
            return datetime.strptime(str(value).strip()[:10], "%Y-%m-%d").date()
        except (ValueError, TypeError):
            pass
        return None

    def _extract_totals(self, row_values: list, result: ParsedStatement) -> None:
        """Extract total debit/credit from the Total row."""
        try:
            dr_val = row_values[COL_DEBIT] if len(row_values) > COL_DEBIT else None
            if dr_val and dr_val != "":
                result.total_debit = Decimal(str(dr_val))
        except (InvalidOperation, ValueError, TypeError):
            pass

        try:
            cr_val = row_values[COL_CREDIT] if len(row_values) > COL_CREDIT else None
            if cr_val and cr_val != "":
                result.total_credit = Decimal(str(cr_val))
        except (InvalidOperation, ValueError, TypeError):
            pass

    def _is_summary_row(self, row_values: list) -> bool:
        """Detect summary/status count rows that are not transactions."""
        first = str(row_values[0]).strip().lower() if row_values[0] else ""
        # Summary rows have a label and optionally a count — no reference code pattern
        if first in ("total", "pending", "complete", "canceled", "time out"):
            return True
        return False

    def _parse_transaction_row(
        self,
        row_values: list,
        row_idx: int,
        sheet,
        row_errors: list,
    ) -> Optional[ParsedTransaction]:
        """Parse a single transaction row."""
        try:
            reference = str(row_values[COL_REFERENCE]).strip()
            if not reference:
                return None

            # Parse datetime
            dt_value = row_values[COL_DATETIME]
            txn_timestamp = self._parse_transaction_datetime(dt_value, sheet, row_idx)
            if txn_timestamp is None:
                row_errors.append(
                    f"Row {row_idx}: Could not parse datetime: {dt_value}"
                )
                return None

            txn_date = txn_timestamp.date()

            description = str(row_values[COL_DESCRIPTION]).strip()

            # Parse monetary values using Decimal
            debit = self._parse_amount(row_values[COL_DEBIT])
            credit = self._parse_amount(row_values[COL_CREDIT])
            balance = self._parse_amount(row_values[COL_BALANCE])

            # Canonical amount: debit = negative (money out), credit = positive (money in)
            amount = Decimal("0")
            if credit and credit > 0:
                amount = credit
            if debit and debit > 0:
                amount = -debit

            status = str(row_values[COL_STATUS]).strip() if len(row_values) > COL_STATUS else ""
            channel = str(row_values[COL_CHANNEL]).strip() if len(row_values) > COL_CHANNEL else ""

            raw_payload = {
                "reference_code": reference,
                "datetime": str(dt_value),
                "description": description,
                "debit": str(debit) if debit else "0",
                "credit": str(credit) if credit else "0",
                "status": status,
                "balance": str(balance) if balance else "",
                "channel": channel,
            }

            return ParsedTransaction(
                source="ESEWA",
                transaction_date=txn_date,
                transaction_timestamp=txn_timestamp,
                description_raw=description,
                debit_amount=debit if debit and debit > 0 else None,
                credit_amount=credit if credit and credit > 0 else None,
                amount=amount,
                balance_after=balance,
                source_reference=reference,
                source_row_number=row_idx,
                raw_payload=raw_payload,
                channel=channel,
            )

        except Exception as e:
            row_errors.append(f"Row {row_idx}: Parse error: {str(e)}")
            return None

    def _parse_transaction_datetime(
        self, value, sheet, row_idx: int
    ) -> Optional[datetime]:
        """Parse transaction datetime from cell value."""
        if isinstance(value, float):
            try:
                dt_tuple = xlrd.xldate_as_tuple(value, sheet.book.datemode)
                return datetime(
                    dt_tuple[0], dt_tuple[1], dt_tuple[2],
                    dt_tuple[3], dt_tuple[4], dt_tuple[5],
                    tzinfo=timezone.utc,
                )
            except Exception:
                pass

        # Try string parsing: "2026-08-07 20:21:25.0"
        str_val = str(value).strip()
        for fmt in [
            "%Y-%m-%d %H:%M:%S.%f",
            "%Y-%m-%d %H:%M:%S",
            "%Y-%m-%d",
        ]:
            try:
                return datetime.strptime(str_val, fmt).replace(tzinfo=timezone.utc)
            except ValueError:
                continue
        return None

    def _parse_amount(self, value) -> Optional[Decimal]:
        """Parse a monetary value to Decimal."""
        if value is None or value == "" or value == "-":
            return None
        try:
            d = Decimal(str(value).strip().replace(",", ""))
            return d
        except (InvalidOperation, ValueError):
            return None
