"""Import orchestration service.

Coordinates the full import pipeline:
upload → hash → create import → parse → validate → reconcile → dedup → insert → result
"""

import hashlib
import logging
import uuid
from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError

from app.models.statement_import import (
    ImportStatus,
    ReconciliationStatus,
    StatementImport,
    StatementSource,
)
from app.models.account import Account
from app.models.transaction import Transaction
from app.parsers.base import ParsedStatement, ParsedTransaction, StatementParser
from app.parsers.esewa import EsewaStatementParser
from app.parsers.nabil import NabilStatementParser
from app.parsers.standard_chartered import StandardCharteredStatementParser
from app.services.deduplication import compute_transaction_hash
from app.services.reconciliation import (
    reconcile_statement,
    validate_running_balance,
)

logger = logging.getLogger(__name__)

# Parser registry
PARSERS: dict[str, StatementParser] = {
    "ESEWA": EsewaStatementParser(),
    "NABIL": NabilStatementParser(),
    "STANDARD_CHARTERED": StandardCharteredStatementParser(),
}


def compute_file_hash(file_bytes: bytes) -> str:
    """Compute SHA-256 hash of uploaded file."""
    return hashlib.sha256(file_bytes).hexdigest()


def import_statement(
    db: Session,
    account_id: uuid.UUID,
    source: str,
    filename: str,
    file_bytes: bytes,
) -> StatementImport:
    """Execute the full statement import pipeline.

    Returns the completed StatementImport record with metrics.
    """
    file_hash = compute_file_hash(file_bytes)

    # Create import record
    stmt_import = StatementImport(
        source=StatementSource(source),
        account_id=account_id,
        filename=filename,
        file_hash=file_hash,
        status=ImportStatus.PARSING,
    )
    db.add(stmt_import)
    db.flush()  # Get the ID

    try:
        # Select parser
        parser = PARSERS.get(source)
        if parser is None:
            stmt_import.status = ImportStatus.FAILED
            stmt_import.error_message = f"Unsupported source: {source}"
            db.commit()
            return stmt_import

        # Parse
        parsed = parser.parse(file_bytes, filename)

        if parsed.errors:
            stmt_import.status = ImportStatus.FAILED
            stmt_import.error_message = "; ".join(parsed.errors[:5])
            stmt_import.row_errors = {"errors": parsed.errors}
            db.commit()
            return stmt_import

        # Update import metadata from parsed results
        stmt_import.period_from = parsed.period_from
        stmt_import.period_to = parsed.period_to
        stmt_import.opening_balance = parsed.opening_balance
        stmt_import.closing_balance = parsed.closing_balance
        stmt_import.currency = parsed.currency
        stmt_import.total_debit = parsed.total_debit
        stmt_import.total_credit = parsed.total_credit
        stmt_import.rows_read = len(parsed.transactions)
        stmt_import.rows_parsed = len(parsed.transactions)

        # Persist the wallet/account number extracted from statement metadata.
        # For eSewa, this is the wallet number from the "Generated by" field.
        # Only update when the parsed value is a meaningful identifier (numeric string),
        # so that a placeholder like ESEWA_DEFAULT gets replaced on first real import.
        if parsed.account_number:
            account = db.query(Account).filter(Account.id == account_id).first()
            if account is not None:
                current = account.account_number or ""
                # Replace placeholder or empty values with the real wallet number.
                is_placeholder = not current or current.upper() in (
                    "ESEWA_DEFAULT", "NABIL_DEFAULT", "DEFAULT", "UNKNOWN"
                )
                if is_placeholder or (parsed.account_number.isdigit() and not current.isdigit()):
                    account.account_number = parsed.account_number
                    db.flush()
                    logger.info(
                        "Updated account %s account_number to %s",
                        account_id, parsed.account_number,
                    )

        # Validate
        stmt_import.status = ImportStatus.VALIDATING

        # Reconcile
        recon_result = reconcile_statement(parsed)

        if recon_result.opening_balance is not None:
            stmt_import.reconciliation_difference = recon_result.difference

            if recon_result.passed:
                stmt_import.reconciliation_status = ReconciliationStatus.PASSED
            else:
                stmt_import.reconciliation_status = ReconciliationStatus.FAILED
                stmt_import.status = ImportStatus.NEEDS_REVIEW
                stmt_import.error_message = (
                    f"Reconciliation failed: difference = {recon_result.difference}"
                )
                # Still continue to insert transactions
        else:
            stmt_import.reconciliation_status = ReconciliationStatus.NOT_AVAILABLE

        # Running balance validation
        if source == "NABIL" and parsed.opening_balance is not None:
            rb_errors = validate_running_balance(
                parsed.transactions,
                opening_balance=parsed.opening_balance,
                reverse_order=False,
            )
            if rb_errors:
                stmt_import.row_errors = stmt_import.row_errors or {}
                stmt_import.row_errors["running_balance_errors"] = rb_errors
                if stmt_import.reconciliation_status != ReconciliationStatus.FAILED:
                    stmt_import.reconciliation_status = ReconciliationStatus.FAILED
                    stmt_import.status = ImportStatus.NEEDS_REVIEW
                    stmt_import.error_message = (
                        f"Running balance validation failed: {len(rb_errors)} errors"
                    )

        elif source == "ESEWA":
            # eSewa is newest-first; validate running balance in reverse
            if parsed.transactions:
                # The opening balance for eSewa can be derived:
                # oldest transaction's balance + its debit - its credit
                oldest_txn = parsed.transactions[-1]  # Last in newest-first order
                if oldest_txn.balance_after is not None:
                    esewa_opening = oldest_txn.balance_after
                    if oldest_txn.debit_amount and oldest_txn.debit_amount > 0:
                        esewa_opening += oldest_txn.debit_amount
                    if oldest_txn.credit_amount and oldest_txn.credit_amount > 0:
                        esewa_opening -= oldest_txn.credit_amount

                    rb_errors = validate_running_balance(
                        parsed.transactions,
                        opening_balance=esewa_opening,
                        reverse_order=True,
                    )
                    if rb_errors:
                        stmt_import.row_errors = stmt_import.row_errors or {}
                        stmt_import.row_errors["running_balance_errors"] = rb_errors

        # Generate hashes and deduplicate
        account_id_str = str(account_id)

        # Fetch existing hashes for this account for dedup
        existing_hashes = set(
            row[0]
            for row in db.query(Transaction.transaction_hash)
            .filter(Transaction.account_id == account_id)
            .all()
        )

        rows_inserted = 0
        duplicate_rows = 0
        invalid_rows = 0

        for txn in parsed.transactions:
            txn_hash = compute_transaction_hash(txn, account_id_str)

            if txn_hash in existing_hashes:
                duplicate_rows += 1
                continue

            # Create transaction record
            db_txn = Transaction(
                source=StatementSource(source),
                account_id=account_id,
                statement_import_id=stmt_import.id,
                transaction_date=txn.transaction_date,
                transaction_timestamp=txn.transaction_timestamp,
                description_raw=txn.description_raw,
                amount=txn.amount,
                debit_amount=txn.debit_amount,
                credit_amount=txn.credit_amount,
                currency=parsed.currency,
                balance_after=txn.balance_after,
                source_reference=txn.source_reference,
                source_row_number=txn.source_row_number,
                transaction_hash=txn_hash,
                raw_payload=txn.raw_payload,
            )

            try:
                db.add(db_txn)
                db.flush()
                rows_inserted += 1
                existing_hashes.add(txn_hash)
            except IntegrityError:
                db.rollback()
                # Re-add the import record after rollback
                db.add(stmt_import)
                db.flush()
                duplicate_rows += 1

        # Update import metrics
        stmt_import.rows_inserted = rows_inserted
        stmt_import.duplicate_rows = duplicate_rows
        stmt_import.invalid_rows = invalid_rows

        if stmt_import.status == ImportStatus.VALIDATING:
            stmt_import.status = ImportStatus.IMPORTED

        stmt_import.completed_at = datetime.now(timezone.utc)
        db.commit()

        # Auto-classify newly imported transactions
        if rows_inserted > 0:
            try:
                from app.services.classification import classify_import_transactions
                classify_import_transactions(db, stmt_import.id)
                logger.info(
                    f"Auto-classified transactions for import {stmt_import.id}"
                )
            except Exception as e:
                logger.warning(
                    f"Auto-classification failed for import {stmt_import.id}: {e}"
                )

        return stmt_import

    except Exception as e:
        db.rollback()
        # Re-create import with failed status
        stmt_import_failed = StatementImport(
            id=stmt_import.id,
            source=StatementSource(source),
            account_id=account_id,
            filename=filename,
            file_hash=file_hash,
            status=ImportStatus.FAILED,
            error_message=str(e)[:1000],
        )
        db.merge(stmt_import_failed)
        db.commit()
        logger.error(f"Import failed for {filename}: {e}", exc_info=True)
        return stmt_import_failed
