"""Initial migration

Revision ID: d10eda928ccc
Revises: 
Create Date: 2026-08-22 21:20:10.244933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd10eda928ccc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('BANK', 'WALLET', name='account_type_enum'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('ESEWA', 'NABIL', name='statement_source_enum'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_parsed', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reconciliation_difference', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reconciliation_status', sa.Enum('PENDING', 'PASSED', 'FAILED', 'NOT_AVAILABLE', name='reconciliation_status_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'VALIDATING', 'READY', 'IMPORTED', 'FAILED', 'NEEDS_REVIEW', name='import_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('row_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('ESEWA', 'NABIL', name='statement_source_enum'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('statement_import_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_clean', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=False),
    sa.Column('transaction_kind', sa.Enum('EXPENSE', 'INCOME', 'INTERNAL_TRANSFER', 'REFUND', 'BANK_FEE', 'INTEREST', 'TAX', 'UNKNOWN', name='transaction_kind_enum'), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('is_internal_transfer', sa.Boolean(), nullable=True),
    sa.Column('transfer_group_id', sa.UUID(), nullable=True),
    sa.Column('classification_source', sa.String(length=50), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['statement_import_id'], ['statement_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'transaction_hash', name='uq_account_transaction_hash')
    )
    op.create_index('ix_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_statement_import_id', 'transactions', ['statement_import_id'], unique=False)
    op.create_index('ix_transactions_transaction_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('ix_transactions_transaction_hash', 'transactions', ['transaction_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_transaction_hash', table_name='transactions')
    op.drop_index('ix_transactions_transaction_date', table_name='transactions')
    op.drop_index('ix_transactions_statement_import_id', table_name='transactions')
    op.drop_index('ix_transactions_account_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('statement_imports')
    op.drop_table('accounts')
    # ### end Alembic commands ###
